import * as Yup from 'yup'

export const productSchema = Yup.object({
  prodNick: Yup.string().required(),
  prodName: Yup.string().required(),
  packGroup: Yup.string(),
  packSize: Yup.number().integer().positive(),
  doughNick: Yup.string(),
  freezerThaw: Yup.bool(),
  packGroupOrder: Yup.number().integer(),
  shapeDay: Yup.number().integer(),
  shapeNick: Yup.string(),
  bakeDay: Yup.number.integer(),
  bakeNick: Yup.string(),
  guarantee: Yup.string(),
  transferStage: Yup.string(),
  readyTime: Yup.number(),
  bakedWhere: Yup.array().of(Yup.string()),
  wholePrice: Yup.number(),
  retailPrice: Yup.number(),
  isWhole: Yup.boolean(),
  weight: Yup.number(),
  descrip: Yup.string(),
  picURL: Yup.string(),
  squareID: Yup.string(),
  forBake: Yup.string(),
  bakeExtra: Yup.number.integer(),
  batchSize: Yup.number.integer(),
  defaultInclude: Yup.boolean(),
  leadTime: Yup.number.integer(),
  qbID: Yup.string(),
})

export const emptyProduct = {
  Type: "", 
  bakeDay: 10, 
  bakeNick: "", 
  bakedWhere: "", 
  descrip: "", 
  doughNick: "", 
  freezerThaw: false, 
  guarantee: "", 
  inventoryProductId: "", 
  isWhole: false, 
  packGroup: "", 
  packGroupOrder: 10, 
  packSize: 10, 
  picURL: "", 
  prodName: "", 
  prodNick: "", 
  readyTime: 1.5, 
  retailPrice: 1.5, 
  shapeDay: 10, 
  shapeNick: "", 
  squareID: "", 
  transferStage: "", 
  weight: 1.5, 
  wholePrice: 1.5,
  forBake: "", 
  bakeExtra: 10, 
  batchSize: 10, 
  defaultInclude: false, 
  leadTime: 10, 
  qbID: "", 

}